services:
  database:
    image: "mysql:8.0"
    container_name: fog-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${FOG_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${FOG_DB_NAME:-fog}"
      MYSQL_USER: "${FOG_DB_USER:-fogmaster}"
      MYSQL_PASSWORD: "${FOG_DB_PASS:-fogmaster123}"
    volumes:
      - "fog_mysql:/var/lib/mysql:rw"
    networks:
      - fog_network
    command: --default-authentication-plugin=mysql_native_password

  fog:
    build:
      context: .
      args:
        FOG_GIT_URL: "${FOG_GIT_URL:-https://github.com/FOGProject/fogproject.git}"
        FOG_GIT_REF: "${FOG_VERSION:-stable}"
    container_name: fog-server
    restart: unless-stopped
    ports:
      - "${FOG_APACHE_PORT:-80}:80"
      - "${FOG_APACHE_SSL_PORT:-443}:443"
      - "69:69/udp"
      - "2049:2049"
      - "21:21"
    environment:
      # Database Configuration
      FOG_DB_HOST: "database"
      FOG_DB_PORT: "3306"
      FOG_DB_NAME: "${FOG_DB_NAME:-fog}"
      FOG_DB_USER: "${FOG_DB_USER:-fogmaster}"
      FOG_DB_PASS: "${FOG_DB_PASS:-fogmaster123}"
      
      # Network Configuration
      FOG_WEB_HOST: "${FOG_WEB_HOST}"
      FOG_WEB_ROOT: "${FOG_WEB_ROOT:-/fog}"
      FOG_TFTP_HOST: "${FOG_TFTP_HOST:-${FOG_WEB_HOST}}"
      FOG_MULTICAST_INTERFACE: "${FOG_MULTICAST_INTERFACE:-eth0}"
      
      # Apache Configuration
      FOG_APACHE_PORT: "80"
      FOG_APACHE_SSL_PORT: "443"
      FOG_HTTPS_ENABLED: "${FOG_HTTPS_ENABLED:-false}"
      
      # Storage Configuration
      FOG_STORAGE_LOCATION: "${FOG_STORAGE_LOCATION:-/images}"
      FOG_STORAGE_CAPTURE: "${FOG_STORAGE_CAPTURE:-/images/dev}"
      
      # FTP Configuration
      FOG_FTP_USER: "${FOG_FTP_USER:-fogproject}"
      FOG_FTP_PASS: "${FOG_FTP_PASS:-fogftp123}"
      
      # Admin Configuration
      FOG_ADMIN_USER: "${FOG_ADMIN_USER:-fog}"
      FOG_ADMIN_PASS: "${FOG_ADMIN_PASS:-password}"
      
      # SSL Configuration
      FOG_SSL_PATH: "/opt/fog/snapins/ssl"
      FOG_SSL_CERT_FILE: "${FOG_SSL_CERT_FILE:-server.crt}"
      FOG_SSL_KEY_FILE: "${FOG_SSL_KEY_FILE:-server.key}"
      FOG_SSL_GENERATE_SELF_SIGNED: "${FOG_SSL_GENERATE_SELF_SIGNED:-true}"
      FOG_SSL_CN: "${FOG_SSL_CN:-${FOG_WEB_HOST}}"
      FOG_SSL_SAN: "${FOG_SSL_SAN:-}"
      
      # Secure Boot Configuration
      FOG_SECURE_BOOT_ENABLED: "${FOG_SECURE_BOOT_ENABLED:-false}"
      FOG_SECURE_BOOT_KEYS_DIR: "${FOG_SECURE_BOOT_KEYS_DIR:-/opt/fog/secure-boot/keys}"
      FOG_SECURE_BOOT_CERT_DIR: "${FOG_SECURE_BOOT_CERT_DIR:-/opt/fog/secure-boot/certs}"
      FOG_SECURE_BOOT_SHIM_DIR: "${FOG_SECURE_BOOT_SHIM_DIR:-/opt/fog/secure-boot/shim}"
      FOG_SECURE_BOOT_MOK_IMG: "${FOG_SECURE_BOOT_MOK_IMG:-/opt/fog/secure-boot/mok-certs.img}"
      
      # DHCP Configuration
      FOG_DHCP_ENABLED: "${FOG_DHCP_ENABLED:-false}"
      FOG_DHCP_START_RANGE: "${FOG_DHCP_START_RANGE:-192.168.1.100}"
      FOG_DHCP_END_RANGE: "${FOG_DHCP_END_RANGE:-192.168.1.200}"
      FOG_DHCP_BOOTFILE: "${FOG_DHCP_BOOTFILE:-undionly.kpxe}"
      FOG_DHCP_DNS: "${FOG_DHCP_DNS:-8.8.8.8}"
      
      # FOG Version
      FOG_VERSION: "${FOG_VERSION:-stable}"
      
      # Data Directory
      FOG_DATA_DIR: "${FOG_DATA_DIR:-/data}"
      
      # Timezone
      TZ: "${TZ:-UTC}"
      
      # Debug
      DEBUG: "${DEBUG:-false}"
      FORCE_FIRST_START_INIT: "${FORCE_FIRST_START_INIT:-false}"
    volumes:
      - "fog_data:/data:rw"
      # Uncomment the following line to mount external SSL certificates
      # - "/path/to/your/ssl/certificates:/opt/fog/snapins/ssl:ro"
    networks:
      - fog_network
    depends_on:
      - database
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

volumes:
  fog_mysql:
    driver: local
  fog_data:
    driver: local

networks:
  fog_network:
    driver: bridge
