services:
  fog-db:
    image: mariadb:10.11
    container_name: fog-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${FOG_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${FOG_DB_NAME:-fog}
      MYSQL_USER: ${FOG_DB_USER:-fogmaster}
      MYSQL_PASSWORD: ${FOG_DB_PASS:-fogmaster123}
    volumes:
      - fog-db-data:/var/lib/mysql
    networks:
      - fog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${FOG_DB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  fog-server:
    image: ghcr.io/88fingerslukee/fog-docker:latest
    container_name: fog-server
    restart: unless-stopped
    depends_on:
      fog-db:
        condition: service_healthy
    privileged: true
    ports:
      - "${FOG_APACHE_EXPOSED_PORT:-80}:${FOG_APACHE_PORT:-80}"
      - "${FOG_APACHE_EXPOSED_SSL_PORT:-443}:${FOG_APACHE_SSL_PORT:-443}"
      - "69:69/udp"
      - "2049:2049"
      - "111:111"
      - "32765:32765"
      - "32767:32767"
      - "21:21"
      - "${FOG_FTP_PASV_MIN_PORT:-21100}-${FOG_FTP_PASV_MAX_PORT:-21110}:${FOG_FTP_PASV_MIN_PORT:-21100}-${FOG_FTP_PASV_MAX_PORT:-21110}"
    volumes:
      - fog-images:/images
      - fog-tftpboot:/tftpboot
      - fog-snapins:/opt/fog/snapins
      - fog-logs:/opt/fog/log
      - fog-ssl:/opt/fog/snapins/ssl
      - fog-config:/opt/fog/config
      - fog-secure-boot:/opt/fog/secure-boot
      # Uncomment the following lines to use host directories instead of Docker volumes:
      # - /path/to/images:/images
      # - /path/to/tftpboot:/tftpboot
      # - /path/to/snapins:/opt/fog/snapins
      # - /path/to/logs:/opt/fog/log
      # - /path/to/ssl:/opt/fog/snapins/ssl
      # - /path/to/config:/opt/fog/config
      # - /path/to/secure-boot:/opt/fog/secure-boot
      # - /path/to/FOG_MIGRATION_DUMP.sql:/opt/migration/FOG_MIGRATION_DUMP.sql  # For FOG database migration
    environment:
      # Database Configuration
      FOG_DB_HOST: "${FOG_DB_HOST:-fog-db}"
      FOG_DB_PORT: "${FOG_DB_PORT:-3306}"
      FOG_DB_NAME: "${FOG_DB_NAME:-fog}"
      FOG_DB_USER: "${FOG_DB_USER:-fogmaster}"
      FOG_DB_PASS: "${FOG_DB_PASS:-fogmaster123}"
      
      # Database Migration Configuration
      FOG_DB_MIGRATION_ENABLED: "${FOG_DB_MIGRATION_ENABLED:-false}"
      FOG_DB_MIGRATION_FORCE: "${FOG_DB_MIGRATION_FORCE:-false}"
      
      # Web Configuration
      FOG_WEB_HOST: "${FOG_WEB_HOST}"
      FOG_WEB_ROOT: "${FOG_WEB_ROOT:-/fog}"
      FOG_APACHE_PORT: "${FOG_APACHE_PORT:-80}"
      FOG_APACHE_SSL_PORT: "${FOG_APACHE_SSL_PORT:-443}"
      
      # SSL Configuration
      FOG_INTERNAL_HTTPS_ENABLED: "${FOG_INTERNAL_HTTPS_ENABLED:-false}"
      FOG_HTTP_PROTOCOL: "${FOG_HTTP_PROTOCOL:-https}"
      FOG_APACHE_SSL_CERT_FILE: "${FOG_APACHE_SSL_CERT_FILE:-server.crt}"
      FOG_APACHE_SSL_KEY_FILE: "${FOG_APACHE_SSL_KEY_FILE:-server.key}"
      FOG_APACHE_SSL_CN: "${FOG_APACHE_SSL_CN:-}"
      FOG_APACHE_SSL_SAN: "${FOG_APACHE_SSL_SAN:-}"
      
      # Network Configuration
      FOG_STORAGE_HOST: "${FOG_STORAGE_HOST:-${FOG_WEB_HOST}}"
      FOG_WOL_HOST: "${FOG_WOL_HOST:-localhost}"
      FOG_MULTICAST_INTERFACE: "${FOG_MULTICAST_INTERFACE:-eth0}"
      
      # FTP Configuration
      FOG_USER: "${FOG_USER:-fogproject}"
      FOG_PASS: "${FOG_PASS:-fogftp123}"
      FOG_FTP_PASV_MIN_PORT: "${FOG_FTP_PASV_MIN_PORT:-21100}"
      FOG_FTP_PASV_MAX_PORT: "${FOG_FTP_PASV_MAX_PORT:-21110}"
      
      # Secure Boot Configuration
      FOG_SECURE_BOOT_ENABLED: "${FOG_SECURE_BOOT_ENABLED:-false}"
      FOG_SECURE_BOOT_KEYS_DIR: "${FOG_SECURE_BOOT_KEYS_DIR:-/opt/fog/secure-boot/keys}"
      FOG_SECURE_BOOT_CERT_DIR: "${FOG_SECURE_BOOT_CERT_DIR:-/opt/fog/secure-boot/certs}"
      FOG_SECURE_BOOT_SHIM_DIR: "${FOG_SECURE_BOOT_SHIM_DIR:-/opt/fog/secure-boot/shim}"
      FOG_SECURE_BOOT_MOK_IMG: "${FOG_SECURE_BOOT_MOK_IMG:-/opt/fog/secure-boot/mok-certs.img}"
      
      # DHCP Configuration
      FOG_DHCP_ENABLED: "${FOG_DHCP_ENABLED:-false}"
      FOG_DHCP_SUBNET: "${FOG_DHCP_SUBNET:-192.168.1.0}"
      FOG_DHCP_NETMASK: "${FOG_DHCP_NETMASK:-255.255.255.0}"
      FOG_DHCP_ROUTER: "${FOG_DHCP_ROUTER:-192.168.1.1}"
      FOG_DHCP_DOMAIN_NAME: "${FOG_DHCP_DOMAIN_NAME:-fog.local}"
      FOG_DHCP_DEFAULT_LEASE_TIME: "${FOG_DHCP_DEFAULT_LEASE_TIME:-600}"
      FOG_DHCP_MAX_LEASE_TIME: "${FOG_DHCP_MAX_LEASE_TIME:-7200}"
      FOG_DHCP_START_RANGE: "${FOG_DHCP_START_RANGE:-192.168.1.100}"
      FOG_DHCP_END_RANGE: "${FOG_DHCP_END_RANGE:-192.168.1.200}"
      FOG_DHCP_BOOTFILE_BIOS: "${FOG_DHCP_BOOTFILE_BIOS:-undionly.kpxe}"
      FOG_DHCP_BOOTFILE_UEFI32: "${FOG_DHCP_BOOTFILE_UEFI32:-ipxe32.efi}"
      FOG_DHCP_BOOTFILE_UEFI64: "${FOG_DHCP_BOOTFILE_UEFI64:-ipxe.efi}"
      FOG_DHCP_BOOTFILE_ARM32: "${FOG_DHCP_BOOTFILE_ARM32:-arm32.efi}"
      FOG_DHCP_BOOTFILE_ARM64: "${FOG_DHCP_BOOTFILE_ARM64:-arm64.efi}"
      FOG_DHCP_HTTPBOOT_ENABLED: "${FOG_DHCP_HTTPBOOT_ENABLED:-false}"
      FOG_DHCP_DNS: "${FOG_DHCP_DNS:-8.8.8.8}"
      FOG_TFTP_HOST: "${FOG_TFTP_HOST}"

      # Timezone
      TZ: "${TZ:-UTC}"
      
      # Debug
      DEBUG: "${DEBUG:-false}"
      FORCE_FIRST_START_INIT: "${FORCE_FIRST_START_INIT:-false}"
    networks:
      - fog-network

volumes:
  fog-db-data:
    driver: local
  fog-images:
    driver: local
  fog-tftpboot:
    driver: local
  fog-snapins:
    driver: local
  fog-logs:
    driver: local
  fog-ssl:
    driver: local
  fog-config:
    driver: local
  fog-secure-boot:
    driver: local

networks:
  fog-network:
    driver: bridge