services:
  # Internal MySQL database
  fog-db:
    image: "mysql:8.0"
    container_name: fog-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${FOG_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${FOG_DB_NAME:-fog}"
      MYSQL_USER: "${FOG_DB_USER:-fogmaster}"
      MYSQL_PASSWORD: "${FOG_DB_PASS:-fogmaster123}"
    volumes:
      - "fog_db:/var/lib/mysql:rw"
    networks:
      - fog_network
    command: --default-authentication-plugin=mysql_native_password

  fog-server:
    build:
      context: .
      args:
        FOG_GIT_URL: "${FOG_GIT_URL:-https://github.com/FOGProject/fogproject.git}"
        FOG_GIT_REF: "${FOG_VERSION:-stable}"
    container_name: fog-server
    restart: unless-stopped
    ports:
      - "${FOG_APACHE_EXPOSED_PORT:-80}:${FOG_APACHE_PORT:-80}"
      - "${FOG_APACHE_EXPOSED_SSL_PORT:-443}:${FOG_APACHE_SSL_PORT:-443}"
      - "69:69/udp"
      - "2049:2049"
      - "111:111"
      - "32765:32765"
      - "32767:32767"
      - "21:21"
    environment:
      # Database Configuration
      FOG_DB_HOST: "${FOG_DB_HOST:-fog-db}"
      FOG_DB_PORT: "${FOG_DB_PORT:-3306}"
      FOG_DB_NAME: "${FOG_DB_NAME:-fog}"
      FOG_DB_USER: "${FOG_DB_USER:-fogmaster}"
      FOG_DB_PASS: "${FOG_DB_PASS:-fogmaster123}"
      
      # Network Configuration
      FOG_WEB_HOST: "${FOG_WEB_HOST}"
      FOG_WEB_ROOT: "${FOG_WEB_ROOT:-/fog}"
      FOG_TFTP_HOST: "${FOG_TFTP_HOST:-localhost}"
      FOG_STORAGE_HOST: "${FOG_STORAGE_HOST:-localhost}"
      FOG_WOL_HOST: "${FOG_WOL_HOST:-localhost}"
      FOG_MULTICAST_INTERFACE: "${FOG_MULTICAST_INTERFACE:-eth0}"
      
      # Apache Configuration
      FOG_APACHE_PORT: "${FOG_APACHE_PORT:-80}"
      FOG_APACHE_SSL_PORT: "${FOG_APACHE_SSL_PORT:-443}"
      FOG_INTERNAL_HTTPS_ENABLED: "${FOG_INTERNAL_HTTPS_ENABLED:-false}"
      FOG_HTTP_PROTOCOL: "${FOG_HTTP_PROTOCOL:-https}"
      
      # FTP Configuration
      FOG_USER: "${FOG_USER:-fogproject}"
      FOG_PASS: "${FOG_PASS:-fogftp123}"
      
      # SSL Configuration
      FOG_SSL_PATH: "/opt/fog/snapins/ssl"
      FOG_SSL_CERT_FILE: "${FOG_SSL_CERT_FILE:-server.crt}"
      FOG_SSL_KEY_FILE: "${FOG_SSL_KEY_FILE:-server.key}"
      FOG_SSL_GENERATE_SELF_SIGNED: "${FOG_SSL_GENERATE_SELF_SIGNED:-true}"
      FOG_SSL_CN: "${FOG_SSL_CN:-${FOG_WEB_HOST}}"
      FOG_SSL_SAN: "${FOG_SSL_SAN:-}"
      
      # Secure Boot Configuration
      FOG_SECURE_BOOT_ENABLED: "${FOG_SECURE_BOOT_ENABLED:-false}"
      FOG_SECURE_BOOT_KEYS_DIR: "${FOG_SECURE_BOOT_KEYS_DIR:-/opt/fog/secure-boot/keys}"
      FOG_SECURE_BOOT_CERT_DIR: "${FOG_SECURE_BOOT_CERT_DIR:-/opt/fog/secure-boot/certs}"
      FOG_SECURE_BOOT_SHIM_DIR: "${FOG_SECURE_BOOT_SHIM_DIR:-/opt/fog/secure-boot/shim}"
      FOG_SECURE_BOOT_MOK_IMG: "${FOG_SECURE_BOOT_MOK_IMG:-/opt/fog/secure-boot/mok-certs.img}"
      
      # DHCP Configuration
      FOG_DHCP_ENABLED: "${FOG_DHCP_ENABLED:-false}"
      FOG_DHCP_SUBNET: "${FOG_DHCP_SUBNET:-192.168.1.0}"
      FOG_DHCP_NETMASK: "${FOG_DHCP_NETMASK:-255.255.255.0}"
      FOG_DHCP_ROUTER: "${FOG_DHCP_ROUTER:-192.168.1.1}"
      FOG_DHCP_DOMAIN_NAME: "${FOG_DHCP_DOMAIN_NAME:-fog.local}"
      FOG_DHCP_DEFAULT_LEASE_TIME: "${FOG_DHCP_DEFAULT_LEASE_TIME:-600}"
      FOG_DHCP_MAX_LEASE_TIME: "${FOG_DHCP_MAX_LEASE_TIME:-7200}"
      FOG_DHCP_START_RANGE: "${FOG_DHCP_START_RANGE:-192.168.1.100}"
      FOG_DHCP_END_RANGE: "${FOG_DHCP_END_RANGE:-192.168.1.200}"
      FOG_DHCP_BOOTFILE_BIOS: "${FOG_DHCP_BOOTFILE_BIOS:-undionly.kpxe}"
      FOG_DHCP_BOOTFILE_UEFI32: "${FOG_DHCP_BOOTFILE_UEFI32:-ipxe32.efi}"
      FOG_DHCP_BOOTFILE_UEFI64: "${FOG_DHCP_BOOTFILE_UEFI64:-ipxe.efi}"
      FOG_DHCP_BOOTFILE_ARM32: "${FOG_DHCP_BOOTFILE_ARM32:-arm32.efi}"
      FOG_DHCP_BOOTFILE_ARM64: "${FOG_DHCP_BOOTFILE_ARM64:-arm64.efi}"
      FOG_DHCP_HTTPBOOT_ENABLED: "${FOG_DHCP_HTTPBOOT_ENABLED:-false}"
      FOG_DHCP_DNS: "${FOG_DHCP_DNS:-8.8.8.8}"
      
      # FOG Version
      FOG_VERSION: "${FOG_VERSION:-stable}"
      
      # Timezone
      TZ: "${TZ:-UTC}"
      
      # Debug
      DEBUG: "${DEBUG:-false}"
      FORCE_FIRST_START_INIT: "${FORCE_FIRST_START_INIT:-false}"
    volumes:
      # FOG Images (main storage - matches bare metal /images)
      - "/files/images:/images:rw"
      
      # TFTP Boot files (matches bare metal /tftpboot)
      - "fog_tftpboot:/tftpboot:rw"
      
      # FOG Snapins (matches bare metal /opt/fog/snapins)
      - "fog_snapins:/opt/fog/snapins:rw"
      
      # FOG Logs (matches bare metal /opt/fog/log)
      - "fog_logs:/opt/fog/log:rw"
      
      # FOG Configuration (persistent config files)
      - "fog_config:/opt/fog/config:rw"
      
      # SSL Certificates (matches bare metal /opt/fog/ssl)
      - "fog_ssl:/opt/fog/ssl:rw"
      
      # Secure Boot files (if enabled)
      - "fog_secure_boot:/opt/fog/secure-boot:rw"
      
      # Uncomment the following lines to mount external directories
      # - "/path/to/your/images:/images:rw"
      # - "/path/to/your/tftpboot:/tftpboot:rw"
      # - "/path/to/your/snapins:/opt/fog/snapins:rw"
      # - "/path/to/your/ssl/certificates:/opt/fog/ssl:ro"
    networks:
      - fog_network
    depends_on:
      - fog-db
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE

volumes:
  # Internal database volume
  fog_db:
    driver: local
  
  # FOG Images storage (main data directory)
  fog_images:
    driver: local
  
  # TFTP Boot files
  fog_tftpboot:
    driver: local
  
  # FOG Snapins
  fog_snapins:
    driver: local
  
  # FOG Logs
  fog_logs:
    driver: local
  
  # FOG Configuration
  fog_config:
    driver: local
  
  # SSL Certificates
  fog_ssl:
    driver: local
  
  # Secure Boot files
  fog_secure_boot:
    driver: local

networks:
  fog_network:
    driver: bridge
